import type { Metadata } from "next";
import Link from "next/link";
import JsonLd, { buildHowToSchema, buildBreadcrumbSchema } from "@/components/JsonLd";
import { Shield, Zap, Eye, Lock, Server, CheckCircle } from "lucide-react";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://plaindoc.app";
const PAGE_URL = `${SITE_URL}/how-it-works`;

export const metadata: Metadata = {
  title: { absolute: "How PlainDoc Works — Plain English Document Explainer" },
  description:
    "Learn how PlainDoc uses AI to explain legal documents in plain English. Privacy-first, no data storage, clause-by-clause explanations in seconds.",
  alternates: { canonical: PAGE_URL },
  openGraph: { url: PAGE_URL },
};

const steps = [
  "Paste the text of your legal document, or upload a PDF file (up to 10 MB).",
  "Select the document type — rental agreement, medical bill, employment contract, and more — to improve accuracy. Or leave it on Auto-detect.",
  "Click 'Explain My Document'. Your document is sent securely to our server over HTTPS.",
  "PlainDoc's AI reads the document and identifies individual clauses, sections, and provisions.",
  "Each clause is summarized in plain English with a severity rating: standard (green), worth noting (amber), or pay attention (red).",
  "Red flags — unusually one-sided or potentially harmful clauses — are surfaced at the top of the results.",
  "Your document is deleted from server memory immediately after the explanation is returned. Nothing is logged or stored.",
  "Review the explanation, note any flagged clauses, and use the insights to make informed decisions before you sign.",
];

const features = [
  {
    icon: Zap,
    title: "Instant Results",
    body: "Get a complete clause-by-clause explanation in seconds, not hours. No waiting, no scheduling, no back-and-forth.",
  },
  {
    icon: Lock,
    title: "Privacy by Design",
    body: "Your document is never stored, logged, or shared. It is processed in server memory and discarded immediately after the explanation is generated.",
  },
  {
    icon: Eye,
    title: "Clause-by-Clause Breakdown",
    body: "We don't just summarize the whole document. Every individual clause is identified, quoted, and explained so you know exactly which part means what.",
  },
  {
    icon: Shield,
    title: "Red Flag Detection",
    body: "Potentially harmful or one-sided clauses — mandatory arbitration, broad IP assignment, aggressive liquidated damages — are automatically flagged for your attention.",
  },
  {
    icon: Server,
    title: "AI-Powered, Human-Reviewed Design",
    body: "Our explanations are generated by large language models trained on millions of legal documents and tested against real-world contracts and agreements.",
  },
  {
    icon: CheckCircle,
    title: "Free, No Account Required",
    body: "PlainDoc is completely free to use. You don't need to create an account or provide any personal information.",
  },
];

export default function HowItWorksPage() {
  return (
    <>
      <JsonLd
        schema={[
          buildBreadcrumbSchema([
            { name: "Home", url: SITE_URL },
            { name: "How It Works", url: PAGE_URL },
          ]),
          buildHowToSchema(
            "How to explain a legal document with PlainDoc",
            steps,
            "Use PlainDoc's free AI tool to get a plain-English, clause-by-clause explanation of any legal document."
          ),
        ]}
      />

      {/* Hero */}
      <section className="bg-gradient-to-b from-indigo-50 to-white py-12 sm:py-16 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-gray-900 mb-4">
            How PlainDoc Works
          </h1>
          <p className="text-lg text-gray-600 leading-relaxed">
            PlainDoc uses AI to read your legal documents and translate every clause into plain,
            simple English — so you know exactly what you&apos;re agreeing to before you sign.
          </p>
        </div>
      </section>

      {/* Steps */}
      <section className="py-12 sm:py-16 px-4 bg-white" aria-labelledby="steps-heading">
        <div className="max-w-3xl mx-auto">
          <h2 id="steps-heading" className="text-2xl sm:text-3xl font-bold text-gray-900 mb-8">
            Step-by-Step Process
          </h2>
          <ol className="space-y-6" role="list">
            {steps.map((step, i) => (
              <li key={i} className="flex items-start gap-4">
                <span className="shrink-0 w-9 h-9 rounded-full bg-indigo-700 text-white text-sm font-bold flex items-center justify-center" aria-hidden="true">
                  {i + 1}
                </span>
                <div className="pt-1.5">
                  <p className="text-gray-700 leading-relaxed">{step}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Features */}
      <section className="py-12 sm:py-16 px-4 bg-gray-50" aria-labelledby="features-heading">
        <div className="max-w-5xl mx-auto">
          <h2 id="features-heading" className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-10">
            Why PlainDoc
          </h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6" role="list">
            {features.map((f) => {
              const Icon = f.icon;
              return (
                <li key={f.title} className="bg-white rounded-2xl border border-gray-200 p-5">
                  <Icon className="w-6 h-6 text-indigo-600 mb-3" aria-hidden="true" />
                  <h3 className="font-bold text-gray-900 mb-2">{f.title}</h3>
                  <p className="text-sm text-gray-600 leading-relaxed">{f.body}</p>
                </li>
              );
            })}
          </ul>
        </div>
      </section>

      {/* Privacy deep-dive */}
      <section className="py-12 sm:py-16 px-4 bg-white" aria-labelledby="privacy-heading">
        <div className="max-w-3xl mx-auto">
          <h2 id="privacy-heading" className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4">
            Our Privacy Commitment
          </h2>
          <p className="text-gray-600 leading-relaxed mb-4">
            Legal documents contain some of the most sensitive information you have — your address, your salary, your medical history, your financial obligations. We take this seriously.
          </p>
          <ul className="space-y-3">
            {[
              "Your document is transmitted over HTTPS (encrypted in transit).",
              "Your document is processed in server memory only — never written to disk or a database.",
              "Your document is discarded immediately after the explanation is generated.",
              "We do not log document content. Ever.",
              "We do not train AI models on your documents.",
              "No account is required — we don't know who you are.",
            ].map((point, i) => (
              <li key={i} className="flex items-start gap-3 text-gray-700 text-sm">
                <CheckCircle className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" aria-hidden="true" />
                {point}
              </li>
            ))}
          </ul>
          <div className="mt-6">
            <Link href="/privacy" className="text-indigo-600 text-sm font-medium hover:text-indigo-800 transition-colors">
              Read our full Privacy Policy →
            </Link>
          </div>
        </div>
      </section>

      {/* Limitations */}
      <section className="py-12 sm:py-16 px-4 bg-amber-50 border-t border-b border-amber-200" aria-labelledby="limitations-heading">
        <div className="max-w-3xl mx-auto">
          <h2 id="limitations-heading" className="text-2xl font-bold text-amber-900 mb-4">
            Important Limitations
          </h2>
          <div className="text-amber-800 space-y-3 text-sm leading-relaxed">
            <p>
              <strong>PlainDoc is not a lawyer and does not provide legal advice.</strong> Our explanations are designed to help you understand what a document says in plain language — not to advise you on whether you should sign it, whether specific clauses are enforceable in your jurisdiction, or what legal action you should take.
            </p>
            <p>
              AI-generated explanations can make mistakes. For documents with significant legal or financial consequences, always have a licensed attorney review the original document.
            </p>
            <p>
              Legal meanings can vary significantly by jurisdiction, industry, and context. A clause that is standard in one state may be unenforceable in another.
            </p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-indigo-700 py-12 px-4">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-white mb-3">
            Ready to Try It?
          </h2>
          <p className="text-indigo-200 mb-6">
            Paste your document and get a plain-English explanation in seconds — completely free.
          </p>
          <Link
            href="/#explain-tool"
            className="inline-flex items-center gap-2 bg-white text-indigo-700 font-bold px-6 py-3 rounded-xl hover:bg-indigo-50 transition-colors"
          >
            Explain My Document — Free
          </Link>
        </div>
      </section>
    </>
  );
}
